name: CutBox cli run testing

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    strategy:
      matrix:
        macos_version:
          - macos-11
          - macos-12
          - macos-13
      fail-fast: false
    runs-on: ${{ matrix.macos_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
          ref: master

      - name: Test cubox_command
        run: |
          test_bin/cutbox -h

          if [ $? == 0 ]; then
            echo "# CutBox precompiled CLI success on ${{ matrix.macos_version }} ðŸ•± âœ… âœ“ âœ— âŒ â˜’ â˜‘ â˜  âŽ ðŸ‘ ðŸ‘Ž ðŸ–’ ðŸ–“" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            test_bin/cutbox -h >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          else
            echo "# CutBox precompiled CLI failed on ${{ matrix.macos_version }} â˜’" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
